### PR TITLE
Properly check if fileList is available

### LINKED ISSUE #408: Can't open files from shared link
**Describe the bug**
Documents in a folder shared by link can not be edited. The app does not open, after entering a nickname there is only a perpetual spinner.

**To Reproduce**
1. Go to a folder shared by link with a password
2. Click on a file such as a text document
3. Enter nickname
4. Observe endless spinner

**Expected behavior**
The richdocuments app should open and allow document editing as it would with a user that is logged in

## Server details

**Operating system**: debian stretch

**Web server:** apache

**Nextcloud version:** 15.0.4

**Version of the richdocuments app** 3.2.1

**Version of Collabora Online** 

LOOLWSD
4.0.0 (git hash: b956fd1)
LOKit
Collabora Office 6.0-23 (git hash: 6410049)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
The relevant part I think is this:

{"reqId":"4NH2Lfjju797MjB54AQk","level":0,"time":"2019-02-17T16:24:10+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 2695","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"4NH2Lfjju797MjB54AQk","level":0,"time":"2019-02-17T16:24:10+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 2695 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"sVzcylze2atRUYBbNsN1","level":0,"time":"2019-02-17T16:24:16+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/public?shareToken=3KLwlO0AO7UyZMR&fileName=Filename.ods&requesttoken=Icbg5JwYnhl%2F8gYUmsIVQ02%2Bb6hk5s4bls71Dhue3f8%3D%3AU5yy1%2FczpmMvwnZx7aVAEQDGXJour7Rd36yBYlf6uK0%3D&fileId=326783","message":"Could not find resource file \"\/apps\/richdocuments\/js\/templates.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"hYJ4GDNtHlIMz97Kj2kw","level":0,"time":"2019-02-17T16:24:16+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/css\/icons\/icons-vars.css?v=1550420441","message":"No cache entry found for \/appdata_ocho1y5xe0y3\/css\/icons\/icons-vars.css.gzip (storage: local::\/var\/nextclouddata\/data\/, internalPath: appdata_ocho1y5xe0y3\/css\/icons\/icons-vars.css.gzip)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"BO5zCajZarAhnJRAykPB","level":0,"time":"2019-02-17T16:24:17+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 2696","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"BO5zCajZarAhnJRAykPB","level":0,"time":"2019-02-17T16:24:17+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 2696 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"KuSOj7fARcqnunUm63RS","level":0,"time":"2019-02-17T16:24:18+00:00","remoteAddr":"172.17.0.2","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/326783_ocho1y5xe0y3?access_token=luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB&access_token_ttl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"1882\",\"owner_uid\":\"Owner\",\"editor_uid\":null,\"fileid\":\"326783\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/nextcloud.NEXTCLOUD.DOMAIN\/\",\"token\":\"luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB\",\"expiry\":\"1550422456\",\"guest_displayname\":\"Guest: aa\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD WOPI Agent 4.0.0","version":"15.0.4.0"}
{"reqId":"B2dT0dIP7ky3QFc1kWEr","level":0,"time":"2019-02-17T16:24:18+00:00","remoteAddr":"172.17.0.2","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/326783_ocho1y5xe0y3\/contents?access_token=luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB&access_token_ttl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"1882\",\"owner_uid\":\"Adrian\",\"editor_uid\":null,\"fileid\":\"326783\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/nextcloud.NEXTCLOUD.DOMAIN\/\",\"token\":\"luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB\",\"expiry\":\"1550422456\",\"guest_displayname\":\"Guest: aa\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD WOPI Agent 4.0.0","version":"15.0.4.0"}

</details>

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #408

### CODE REVIEW

File: js/documents.js [hunk 1]
```diff
@@ -838,7 +848,7 @@ var documentsMain = {
 		}
 
 		documentsMain.ready = true;
-		if (parent && parent.OCA.Files.App.fileList.reload) {
+		if (parent && documentsMain.getFileList() !== null) {
 			parent.OCA.Files.App.fileList.reload();
```
Comment (ljo) [inline js/documents.js]: Must not all uses of parent.OCA.Files.App.fileList be replaced by documentsMain.getFileList()?

Comment (juliushaertl) [reply js/documents.js]: Good catch, thanks :+1:
